"""license workflow refactor

Revision ID: 31744d73fce5
Revises: 20251023162412
Create Date: 2025-10-23 20:12:24.805522
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '31744d73fce5'
down_revision = '20251023162412'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admin_notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('payload', sa.Text(), nullable=True),
        sa.Column('is_read', sa.Boolean(), server_default=sa.text("0"), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notifications_admin_id'), 'admin_notifications', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_notifications_id'), 'admin_notifications', ['id'], unique=False)
    op.create_table(
        'license_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('plan_name', sa.String(), nullable=False),
        sa.Column('max_devices', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('device_id', sa.String(), nullable=False),
        sa.Column('device_name', sa.String(), nullable=True),
        sa.Column('device_info', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('admin_notes', sa.Text(), nullable=True),
        sa.Column('device_secret', sa.String(), nullable=True),
        sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('decided_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_requests_id'), 'license_requests', ['id'], unique=False)
    op.create_index(op.f('ix_license_requests_status'), 'license_requests', ['status'], unique=False)
    op.create_index(op.f('ix_license_requests_user_id'), 'license_requests', ['user_id'], unique=False)
    with op.batch_alter_table('devices') as batch_op:
        batch_op.add_column(sa.Column('secret_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hardware_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('licenses') as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('ix_licenses_request_id', ['request_id'])
        batch_op.create_foreign_key('fk_licenses_request_id', 'license_requests', ['request_id'], ['id'])
        batch_op.create_foreign_key('fk_licenses_approved_by', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenses') as batch_op:
        batch_op.drop_constraint('fk_licenses_request_id', type_='foreignkey')
        batch_op.drop_constraint('fk_licenses_approved_by', type_='foreignkey')
        batch_op.drop_index('ix_licenses_request_id')
        batch_op.drop_column('issued_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('request_id')

    with op.batch_alter_table('devices') as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('hardware_info')
        batch_op.drop_column('secret_hash')
    op.drop_index(op.f('ix_license_requests_user_id'), table_name='license_requests')
    op.drop_index(op.f('ix_license_requests_status'), table_name='license_requests')
    op.drop_index(op.f('ix_license_requests_id'), table_name='license_requests')
    op.drop_table('license_requests')
    op.drop_index(op.f('ix_admin_notifications_id'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_admin_id'), table_name='admin_notifications')
    op.drop_table('admin_notifications')
    # ### end Alembic commands ###

